# x=open("text.txt","x")
y=open("text.txt","w")
y.write("my name is sreeshna\n")
y.write("iam a data analyst student\n")
y.close()
y=open("text.txt","a")
y.write("iam from ernakulam")
y.close()
y=open("text.txt","r")
z=y.read()
print(z)
y.close()
y=open("text.txt","r")
print(y.read(7))
y.close()
y=open("text.txt","r")
print(y.readline())
print(y.readline())
y.close()
# z=open("handling.txt","x")
import os
# os.remove("handling.txt")
os.rmdir("filehandling")