# x=open("f4.txt","x")
y=open("f4.txt","w")
y.write("my name is sreeshna")
y.close()
y=open("f4.txt","r")
z=y.read()
y.close()
# x=open("f5.txt","x")
a=open("f5.txt","w")
a.write("iam from ernakulam")
a.close()
a=open("f5.txt","r")
b=a.read()
a.close()
# x=open("f6.txt","x")
c=open("f6.txt","w")
c.write("iam a data analyst student")
c.close()
c=open("f6.txt","r")
d=c.read()
c.close()
# x=open("f7.txt","x")
e=open("f7.txt","w")
e.write(z)
e.write(b)
e.write(d)


